catch {::common::set_param -quiet hls.xocc.mode csynth};
# 
# HLS run script generated by v++ compiler
# 
open_project strassensSquaredKernel
set_top uut_top
# v++ -g, -D, -I, --advanced.prop kernel.blasKernel.kernel_flags
# The user needs to adjust these paths according to their own project structure
add_files "/home/aahmadaa/blocked_systolic_array/src/L2/tests/gemm_1CU/tb_squared/uut_top.cpp" -cflags " -g -I /home/aahmadaa/blocked_systolic_array/src/L1/include/hw -I /home/aahmadaa/blocked_systolic_array/src/L1/include/hw/xf_blas -I /home/aahmadaa/blocked_systolic_array/src/L1/include/hw/xf_blas/gemm -I /home/aahmadaa/blocked_systolic_array/src/L1/include/hw/xf_blas/helpers/utils -I /home/aahmadaa/blocked_systolic_array/src/L2/include -I /home/aahmadaa/blocked_systolic_array/src/L2/include/hw/xf_blas -I /home/aahmadaa/blocked_systolic_array/src/L1/include/hw -I /home/aahmadaa/blocked_systolic_array/src/L2/src/hw -I /home/aahmadaa/blocked_systolic_array/src/L2/tests/gemm_1CU/tb_squared"

add_files -tb "/home/aahmadaa/blocked_systolic_array/src/L2/tests/gemm_1CU/tb_squared/mmult_test.cpp" -cflags " -g -I /home/aahmadaa/blocked_systolic_array/src/L1/include/hw -I /home/aahmadaa/blocked_systolic_array/src/L1/include/hw/xf_blas -I /home/aahmadaa/blocked_systolic_array/src/L1/include/hw/xf_blas/gemm -I /home/aahmadaa/blocked_systolic_array/src/L1/include/hw/xf_blas/helpers/utils -I /home/aahmadaa/blocked_systolic_array/src/L2/include -I /home/aahmadaa/blocked_systolic_array/src/L2/include/hw/xf_blas -I /home/aahmadaa/blocked_systolic_array/src/L1/include/hw -I /home/aahmadaa/blocked_systolic_array/src/L2/src/hw -I /home/aahmadaa/blocked_systolic_array/src/L2/tests/gemm_1CU/tb_squared"

open_solution -flow_target vitis solution
set_part xcu50-fsvh2104-2-e
# v++ --hls.clock or --kernel_frequency
create_clock -period 300MHz -name default
# v++ --advanced.param compiler.hlsDataflowStrictMode
config_dataflow -strict_mode warning
# v++ --advanced.param compiler.deadlockDetection
config_export -deadlock_detection sim
# v++ --advanced.param compiler.axiDeadLockFree
config_interface -m_axi_conservative_mode=1
config_interface -m_axi_addr64
# v++ --hls.max_memory_ports
config_interface -m_axi_auto_max_ports=0
# config_export -format xo -ipname blasKernel

# Uncomment the following line to according to your need
# Can do csim, csynth, cosim, export_design
csim_design
# csynth_design
# cosim_design
# export_design
close_project
puts "HLS completed successfully"
exit
